### PR TITLE
support asset-data-url transformation

### PR DESCRIPTION
**Pull request by jbach**

### CODE REVIEW

**Review by rstacruz — APPROVED** [review]
Amazing! Thanks!

**Comment by rstacruz** [comment]
Thanks for your contribution! 😍 Curious: What do you use this package for?

**Comment by jbach** [comment]
No worries 👍  We are using it in combination with npm-pipeline-rails. Building our frontend assets via (webpack | gulp | grunt) while still serving the files via rails’ asset pipeline.

**Comment by jbach** [comment]
Hey @rstacruz, do you think you could `npm publish` a new version?

**Pull request merged**
